[build]
  base = "web"
  command = "npx prisma generate && npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
