[phases.setup]
nixPkgs = ["bun", "openssl_3", "sqlite"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bunx prisma generate"]

[start]
cmd = "ENVIRONMENT=production bash scripts/start"
